pragma solidity ^0.8.17;

contract vcapitalPool {
    mapping(address(mapping=>uint256))) public stakedBalances;
    //stakedBalances is a mapping of addresses to a mapping of addresses to uint256
    //stakedBalances is the amount of tokens that are staked by an address
    //stakedBalances is the amount of tokens that are staked by an address on a specific token
    member[] public memberList;
    //memberList is an array of member structs
    struct member {
        string name;
        //name is the name of the member
        string url;
        //url is the url of the member
        uint256 id;
        //id is the id of the member
        uint256[] influencerList;
        //influencerList is the list of influencers that are supported by the protocol
    }
    //LP Liquidity Pool
    //LPs are the people who provide liquidity to the protocol
    //LPs are rewarded with a portion of the fees generated by the protocol
    //LPs stake their tokens to the protocol and they are granted one Vote
    function addLiquidity() public {  
    }
    loanProtocol();
}
